// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CallClaudeCode(arg1:string):Promise<string>;

export function CheckGitRepoExists():Promise<boolean>;

export function CommitChanges(arg1:string):Promise<void>;

export function GetCommitHistory():Promise<Array<string>>;

export function GetRepoFiles():Promise<Array<string>>;

export function GetSelectedRepo():Promise<string>;

export function Greet(arg1:string):Promise<string>;

export function InitializeLocalGitRepo():Promise<void>;

export function ReadFile(arg1:string):Promise<string>;

export function SelectRepository():Promise<string>;

export function WriteFile(arg1:string,arg2:string):Promise<void>;
