// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CallClaudeCode(arg1) {
  return window['go']['main']['App']['CallClaudeCode'](arg1);
}

export function CheckGitRepoExists() {
  return window['go']['main']['App']['CheckGitRepoExists']();
}

export function CommitChanges(arg1) {
  return window['go']['main']['App']['CommitChanges'](arg1);
}

export function GetCommitHistory() {
  return window['go']['main']['App']['GetCommitHistory']();
}

export function GetRepoFiles() {
  return window['go']['main']['App']['GetRepoFiles']();
}

export function GetSelectedRepo() {
  return window['go']['main']['App']['GetSelectedRepo']();
}

export function Greet(arg1) {
  return window['go']['main']['App']['Greet'](arg1);
}

export function InitializeLocalGitRepo() {
  return window['go']['main']['App']['InitializeLocalGitRepo']();
}

export function ReadFile(arg1) {
  return window['go']['main']['App']['ReadFile'](arg1);
}

export function SelectRepository() {
  return window['go']['main']['App']['SelectRepository']();
}

export function WriteFile(arg1, arg2) {
  return window['go']['main']['App']['WriteFile'](arg1, arg2);
}
